# Generated by Django 6.0.2 on 2026-03-04 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acronimo', models.CharField(help_text='Ex: IFG', max_length=10, unique=True)),
                ('nome_completo', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoIdentificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_identificacao', models.DateField()),
                ('observacoes_identificacao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroColeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_coleta', models.DateField()),
                ('pais', models.CharField(default='Brasil', max_length=50)),
                ('estado_provincia', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=100)),
                ('localidade', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('habitat', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_tombo', models.CharField(help_text='Código de Barras', max_length=50, unique=True)),
                ('num_coleta', models.CharField(help_text='Número do coletor', max_length=50)),
                ('tipo_status', models.CharField(blank=True, help_text='Ex: Holótipo, Isótipo', max_length=50)),
                ('status_submissao', models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovado', 'Aprovado')], default='Pendente', max_length=20)),
                ('data_aprovacao', models.DateField(blank=True, null=True)),
                ('id_colecao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herbarium.colecao')),
                ('id_identificacao_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencia_atual', to='herbarium.historicoidentificacao')),
            ],
        ),
        migrations.CreateModel(
            name='ImagemEspecime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(upload_to='herbário/imagens/')),
                ('tipo_imagem', models.CharField(blank=True, max_length=50)),
                ('data_registro', models.DateField(auto_now_add=True)),
                ('id_ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='herbarium.ocorrencia')),
            ],
        ),
        migrations.AddField(
            model_name='historicoidentificacao',
            name='id_ocorrencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_identificacoes', to='herbarium.ocorrencia'),
        ),
        migrations.CreateModel(
            name='ComplementoEspecime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_complemento', models.CharField(help_text='DNA, Carpoteca, Lâmina', max_length=50)),
                ('identificador_complemento', models.CharField(blank=True, max_length=100)),
                ('local_armazenamento', models.CharField(max_length=100)),
                ('observacoes', models.TextField(blank=True)),
                ('id_ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herbarium.ocorrencia')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=150)),
                ('acronimo_coletor', models.CharField(help_text='Ex: A. Silva', max_length=50)),
                ('instituicao', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nivel_acesso', models.CharField(choices=[('ALUNO', 'Aluno'), ('CURADOR', 'Curador'), ('ADMIN', 'Administrador')], max_length=20)),
                ('status_conta', models.CharField(default='Ativa', max_length=20)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OcorrenciaColetor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_principal', models.BooleanField(default=False)),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herbarium.ocorrencia')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herbarium.pessoa')),
            ],
            options={
                'unique_together': {('ocorrencia', 'pessoa')},
            },
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='coletores',
            field=models.ManyToManyField(related_name='coletas_participadas', through='herbarium.OcorrenciaColetor', to='herbarium.pessoa'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='id_aprovador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias_aprovadas', to='herbarium.pessoa'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='id_digitador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ocorrencias_digitadas', to='herbarium.pessoa'),
        ),
        migrations.AddField(
            model_name='historicoidentificacao',
            name='id_identificador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='herbarium.pessoa'),
        ),
        migrations.AddField(
            model_name='colecao',
            name='curador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='herbarium.pessoa'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='id_registro_coleta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herbarium.registrocoleta'),
        ),
        migrations.CreateModel(
            name='Taxonomia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cientifico', models.CharField(help_text='Gênero + Espécie + Autor', max_length=255, unique=True)),
                ('autor', models.CharField(blank=True, max_length=100)),
                ('familia', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=100)),
                ('epiteto_especifico', models.CharField(blank=True, max_length=100)),
                ('status_taxonomico', models.CharField(choices=[('Aceito', 'Aceito'), ('Sinônimo', 'Sinônimo')], default='Aceito', max_length=30)),
                ('id_nome_aceito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sinonimos', to='herbarium.taxonomia')),
            ],
        ),
        migrations.AddField(
            model_name='historicoidentificacao',
            name='id_taxon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herbarium.taxonomia'),
        ),
    ]
