# Generated by Django 6.0.2 on 2026-03-10 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbarium', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colecao',
            old_name='curador',
            new_name='id_curador',
        ),
        migrations.RemoveField(
            model_name='complementoespecime',
            name='identificador_complemento',
        ),
        migrations.RemoveField(
            model_name='complementoespecime',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='historicoidentificacao',
            name='observacoes_identificacao',
        ),
        migrations.RemoveField(
            model_name='imagemespecime',
            name='tipo_imagem',
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='data_aprovacao',
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='id_aprovador',
        ),
        migrations.AlterField(
            model_name='colecao',
            name='acronimo',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='complementoespecime',
            name='tipo_complemento',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='historicoidentificacao',
            name='id_ocorrencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='herbarium.ocorrencia'),
        ),
        migrations.AlterField(
            model_name='imagemespecime',
            name='url',
            field=models.ImageField(upload_to='herbarium/fotos/'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='coletores',
            field=models.ManyToManyField(through='herbarium.OcorrenciaColetor', to='herbarium.pessoa'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='id_digitador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='digitacoes', to='herbarium.pessoa'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='id_identificacao_atual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencia_principal', to='herbarium.historicoidentificacao'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='num_coleta',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='num_tombo',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='tipo_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='acronimo_coletor',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='taxonomia',
            name='nome_cientifico',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
